### ISSUE TITLE
register package

### ISSUE THREAD

**Issue by lazarusA** [asinghvi17/SwarmMakie.jl#10]
I had been using this package lately. No problems so far. Maybe registering it would be nice 😄.

**Comment by asinghvi17** [comment]
We could!  @TheCedarPrince is this ready for your use?

**Comment by TheCedarPrince** [comment]
Yea! I have actually already been using it @asinghvi17. The outstanding question I have is if we are planning to upstream it to Makie at some point, does it make sense to release it as its own standalone package? Or what else is left before upstreaming? 

Also, cool to hear that you've been using it @lazarusA ! :smile: 

I'd be fine with releasing it, but just wondering if we should target upstreaming first instead of release. Thoughts Anshul?

**Comment by asinghvi17** [comment]
Since this is a bit complex (and I have been considering a kind of force-directed algorithm which would give pretty optimal packing), I think we should keep it a separate package for now.  We can always avoid breakage after upstreaming by simply re-exporting the relevant Makie symbols.

Plus, if anyone finds a bug in the algorithms, it's easier to patch and release now than it would be if it's in base Makie as well.

**Comment by TheCedarPrince** [comment]
That makes a lot of sense! Alright, then let's release it. :smiley: 

P.S. What is the algorithm you are mentioning? Does it come from a paper somewhere? Just curious.

**Comment by asinghvi17** [comment]
No, it's a pretty simple idea (but a bit wasteful computationally).  It would basically be each marker repelling the others and itself moving in the y-direction, while simultaneously being attracted to the origin, to try and create optimal packing.  I'm sure it's not the most efficient but it would be a fun experiment :D.
